workflows:
  android-debug:
    name: Android Debug
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK debug
        script: flutter build apk --debug --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
    publishing:
      email:
        recipients:
          - seu@email.com
        notify:
          success: true
          failure: true
